# Generated by Django 6.0.1 on 2026-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pg_audit_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('table_name', models.TextField()),
                ('action', models.TextField()),
                ('row_pk', models.TextField(blank=True, null=True)),
                ('changed_by', models.TextField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-occurred_at'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('access_it_portal', 'Can access IT portal'), ('access_hr_portal', 'Can access HR portal'), ('access_sales_portal', 'Can access Sales portal'), ('access_audit_portal', 'Can access Audit portal')]},
        ),
    ]
